# Generated by Django 4.2.5 on 2024-03-20 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
        ('quickstart', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='church',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='church', to='church.church'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(default=3),
        ),
    ]
