# Generated by Django 4.2.5 on 2024-03-20 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
        ('quickstart', '0003_remove_user_is_admin_user_church_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church', to='church.church'),
        ),
    ]
