# Generated by Django 4.2.5 on 2024-03-20 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
        ('quickstart', '0004_alter_user_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='church',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='church.church'),
        ),
    ]
