# Generated by Django 4.2.5 on 2024-03-20 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_alter_user_church'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='church',
        ),
    ]
