# Generated by Django 4.2.5 on 2024-03-20 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_alter_church_id'),
        ('quickstart', '0006_remove_user_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='church',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='church.church'),
            preserve_default=False,
        ),
    ]
