# Generated by Django 4.2.5 on 2024-04-24 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_alter_meeting_church_alter_meeting_created_by'),
        ('tasks', '0008_alter_task_church_alter_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='meeting_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='meeting.meeting'),
        ),
    ]
