# Generated by Django 4.2.5 on 2024-11-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_person_church'),
        ('tasks', '0011_task_meeting_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='task',
            name='employees',
            field=models.ManyToManyField(to='person.person'),
        ),
    ]
