# Generated by Django 4.2.5 on 2024-03-21 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_alter_church_id'),
        ('requestuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestuser',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.church'),
        ),
        migrations.AlterField(
            model_name='requestuser',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
