# Generated by Django 4.2.5 on 2024-03-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestuser', '0005_requestuser_approval_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
