# Generated by Django 4.2.5 on 2024-11-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_alter_meeting_church_alter_meeting_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='action_steps',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='objective',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='questions',
            field=models.TextField(default=''),
        ),
    ]
