# Generated by Django 4.2.5 on 2024-11-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_meeting_action_steps_meeting_objective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='notes_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
