# Generated by Django 4.2.5 on 2024-11-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0010_meeting_notes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='notes_image',
            field=models.ImageField(blank=True, null=True, upload_to='meeting_notes/'),
        ),
    ]
