# Generated by Django 4.2.5 on 2024-11-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0011_alter_meeting_notes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='notes_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
