# Generated by Django 4.2.5 on 2024-04-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_church_subscription'),
        ('person', '0002_person_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personchurch', to='church.church'),
        ),
    ]
