# Generated by Django 4.2.5 on 2024-04-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
