# Generated by Django 4.2.5 on 2024-03-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_alter_church_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
