# Generated by Django 4.2.5 on 2024-03-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_alter_church_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='address',
            field=models.CharField(default='Home', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='ph_no',
            field=models.CharField(default='111-111-1111', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='website',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
