# Generated by Django 4.2.5 on 2024-04-08 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_count'),
        ('church', '0004_church_address_church_email_church_ph_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='churchSubscription', to='subscription.subscription'),
        ),
    ]
