# Generated by Django 4.2.5 on 2024-04-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_church_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='ph_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
