# Generated by Django 4.2.5 on 2024-05-01 05:47

from datetime import datetime
from django.db import migrations, models
import pytz


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_alter_church_address_alter_church_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now(pytz.utc)),
            preserve_default=False,
        ),
    ]
