# Generated by Django 4.2.5 on 2024-05-01 00:14

from datetime import datetime
import pytz
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_alter_church_address_alter_church_name_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.now(pytz.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default="test@email.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='success',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.church'),
        ),
    ]
