# Generated by Django 4.2.5 on 2024-05-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_amount_payment_date_payment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
