# Generated by Django 4.2.5 on 2024-05-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
